language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

addons:
    code_climate:
        repo_token: ed81a58af0f4f82d772972f3343d9daadaa13ce6b591d267ef5c1a3c824a3a37

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter